config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    root to: 'messages#index'

    resources :messages do
      patch :good, on: :member
      patch :bad, on: :member
    end

    resources :classifier_features, only: [:index, :edit, :new, :create, :update, :destroy]
  end
end

app/models/classifier_feature.rb
class ClassifierFeature < ActiveRecord::Base
  validates :category, presence: true
  validates :name, presence: true, uniqueness: {:scope => :category}

  def good?
    category.to_sym == :good
  end

  def bad?
    category.to_sym == :bad
  end

  def self.categories
    [:good, :bad]
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, presence: true
  validates :language, presence: true

  def good?
    category.to_sym == :good
  end

  def bad?
    category.to_sym == :bad
  end

  def save
    self.category = ClassifyService.classify(self.body).to_sym
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/flash_helper.rb
module Concerns
  module FlashHelper
    def f(key, options = {})
      scope = [:flash]

      default_scope = scope.dup
      default_scope << 'base' << params[:action]

      default_msg = I18n.t(key, scope: default_scope)

      current_scope = scope.dup
      current_scope << params[:controller].split('/')
      current_scope << params[:action]

      msg = I18n.t(key, scope: current_scope, default: default_msg)
      Rails.logger.debug(msg)
      if options[:now]
        flash.now[key] = msg
      else
        flash[key] = msg
      end
    end
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include Concerns::FlashHelper
end

app/controllers/web/classifier_features_controller.rb
class Web::ClassifierFeaturesController < Web::ApplicationController
  before_action :set_classifier_feature, except: [:create, :index, :new]

  def index
    query = params[:q] || {}
    @search = ClassifierFeature.ransack query
    @classifier_features = @search.result.page(params[:page]).decorate
  end

  def new
    @classifier_feature = ClassifierFeature.new
  end

  def edit
  end

  def create
    @classifier_feature = ClassifierFeature.new(classifier_feature_params)

    if @classifier_feature.save
      f(:success)
      redirect_to classifier_features_path
    else
      f(:error)
      render action: 'new'
    end
  end

  def update
    if @classifier_feature.update(classifier_feature_params)
      f(:success)
      redirect_to classifier_features_path
    else
      f(:error)
      render action: 'edit'
    end
  end

  def destroy
    @classifier_feature.destroy
    f(:success)
    redirect_to classifier_features_url, notice: 'ClassifierFeature was successfully destroyed.'
  end

  private

  def set_classifier_feature
    @classifier_feature = ClassifierFeature.find(params[:id])
  end

  def classifier_feature_params
    params.require(:classifier_feature).permit(:name, :category, :count)
  end
end

app/controllers/web/messages_controller.rb
class Web::MessagesController < Web::ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  def index
    query = params[:q] || {}
    @search = Message.ransack query
    @messages = @search.result.page(params[:page]).decorate
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = Message.new(message_params)

    if @message.save
      f(:success)
      redirect_to messages_path
    else
      f(:error)
      render :new
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      f(:success)
      redirect_to messages_path
    else
      f(:error)
      render :edit
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  def good
    ClassifyService.train(@message.text, :good, @message.language)
    @message.category = :good
    @message.save!

    redirect_to action: :index
  end

  def bad
    ClassifyService.train(@message.text, :bad, @message.language)

    @message.category = :bad
    @message.save!

    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:body, :category, :language, :external_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_search_form_options(options = {})
    { method: 'get', html: { class: 'form-search' }, defaults: { label: false, required: false } }.merge(options)
  end

  def edit_and_destroy_buttons(edit_path, destroy_path)
    content_tag :div, class: 'btn-group' do
      link_to('Edit', edit_path, edit_button_params) +
      link_to('Destroy', destroy_path, destroy_button_params)
    end
  end

  def edit_and_destroy_buttons_vertical(edit_path, destroy_path)
    content_tag :div, class: 'btn-group-vertical' do
      link_to('Edit', edit_path, edit_button_params) +
      link_to('Destroy', destroy_path, destroy_button_params)
    end
  end

  def admin_destroy_button(path)
    link_to 'Destroy', path, destroy_button_params.merge(class: 'btn btn-danger')
  end

  def right_button_params
    { class: 'btn btn-default pull-right', role: 'button' }
  end

  def edit_button_params
    { class: 'btn btn-primary', role: 'button' }
  end

  def destroy_button_params
    {
      method: :delete,
      data: { confirm: 'Are you sure?' },
      class: 'btn btn-danger',
      role: 'button'
    }
  end

  def real_f(real)
    format('%.3f', real)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "ScamTest"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    .main
      = nav_bar fixed: :top, brand: "ScamTest", brand_link: root_path do
        = menu_group do
          = menu_item t('messages'), messages_path
          = menu_item t('classifier'), classifier_features_path

      %br
      %br
      %br
      .container.base-content
        .row
          .col-lg-12
            = bootstrap_flash
            = yield
    %footer
      %p &copy; avk@8xx8.ru

app/views/web/classifier_features/_form.html.haml
= simple_form_for @classifier_feature, url: url, html: {class: "form-horizontal"} do |f|
  = f.error_notification

  = f.input :name
  = f.input :category
  = f.input :count

  .form-group
    .col-sm-10.col-sm-offset-2
      = f.button :submit

app/views/web/classifier_features/edit.html.haml
%h1 Editing classifier_feature

%hr

= render 'form', url: classifier_feature_path(@classifier_feature)

%br
= link_to t('back'), classifier_features_path

app/views/web/classifier_features/index.html.haml
%h1
  ClassifierFeatures
  = link_to '+ New ClassifierFeature', new_classifier_feature_path, class: "btn btn-default"

%hr

.well
  = simple_form_for @search, default_search_form_options(url: classifier_features_path, html: {class: "form-inline"}) do |f|
    .form-group
      = f.input_field :name_cont
    .form-group
      = f.submit class: 'btn', value: 'Search'

= paginate @classifier_features

.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th #
        %th= sort_link @search, :name
        %th= sort_link @search, :category
        %th= sort_link @search, :count
        %th

    %tbody
      - @classifier_features.each do |classifier_feature|
        %tr
          %td= classifier_feature.id
          %td= classifier_feature.name
          %td
            %span{ class: "label #{classifier_feature.category_class}" }
              = classifier_feature.category
          %td= classifier_feature.count
          %td.text-right= edit_and_destroy_buttons(edit_classifier_feature_path(classifier_feature), classifier_feature_path(classifier_feature))

= paginate @classifier_features

app/views/web/classifier_features/new.html.haml
%h1 New classifier_feature

%hr

= render 'form', url: classifier_features_path

%br
= link_to t('back'), classifier_features_path

app/views/web/messages/_form.html.erb
<%= form_for @message, :html => { :class => "form-horizontal message" } do |f| %>

    <% if @message.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :body, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:body]) %>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:category]) %>
  </div>
  <div class="control-group">
    <%= f.label :language, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :language, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:language]) %>
  </div>
  <div class="control-group">
    <%= f.label :external_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :external_id, :class => 'form-control' %>
    </div>
    <%= error_span(@message[:external_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            messages_path, :class => 'btn btn-default' %>

<% end %>

app/views/web/messages/edit.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/web/messages/index.html.haml
%h1
  Messages
  = link_to '+ New Message', new_message_path, class: "btn btn-default"

%hr

.well
  = simple_form_for @search, default_search_form_options(url: messages_path, html: {class: "form-inline"}) do |f|
    .form-group
      = f.input_field :external_id_eq
    .form-group
      = f.submit class: 'btn', value: 'Search'

= paginate @messages

.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th #
        %th= sort_link @search, :body
        %th= sort_link @search, :category
        %th= sort_link @search, :external_id
        %th

    %tbody
      - @messages.each do |message|
        %tr
          %td= message.id
          %td
            = message.body
            %hr
            - meta = Classifier.meta_classify(message.body)
            - meta[:categories].each do |category|
              = "#{category[:name]} (#{real_f(category[:fisher_prob])})"
              - meta[:features].each do |feature|
                - feature_cat = feature[:categories].find { |c| c[:name] == category[:name] }
                = feature[:name]
                = real_f(feature_cat[:weighted_prob])
              %hr

          %td
            %span{ class: "label #{message.category_class}" }
              = message.category
          %td= message.external_id
          %td.text-right
            = link_to t('mark_good'), good_message_path(message), class: 'btn btn-success', method: :patch
            = link_to t('mark_bad'), bad_message_path(message), class: 'btn btn-warning', method: :patch
            = edit_and_destroy_buttons(edit_message_path(message), message_path(message))

= paginate @messages

app/views/web/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/web/messages/show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @message.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @message.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @message.language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:external_id) %>:</strong></dt>
  <dd><%= @message.external_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              messages_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_message_path(@message), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>